name: Build qBittorrent + deps for JDCloud RE-SP-01B (ramips/mt7621)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python2.7 python2.7-dev unzip zlib1g-dev file wget
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
          

    - name: Download OpenWrt 19.07.9 SDK (ramips/mt7621)
      run: |
        export OWRT_VER="19.07.9"
        export ARCH="ramips/mt7621"
        export SDK_URL="https://downloads.openwrt.org/releases/19.07.9/targets/ramips/mt7621/openwrt-sdk-19.07.9-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64.tar.xz"
       
        wget $SDK_URL
        tar -Jxf openwrt-sdk-*.tar.xz
        rm -rf sdk 
        mv openwrt-sdk-19.07.9-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64 sdk

    - name: Clone qBittorrent package (for-openwrt-19.7)
      run: |
        cd sdk/package
        git clone -b for-openwrt-19.07 https://github.com/KryptonLee/qBittorrent-openwrt-package.git qbittorrent

    - name: Update feeds
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure
      run: |
        cd sdk
        make defconfig
        # 强制启用 boost-system 以避免依赖缺失
        echo "CONFIG_PACKAGE_boost=y" >> .config
        echo "CONFIG_PACKAGE_boost-system=y" >> .config
        make defconfig

    - name: Build all deps (boost + rblibtorrent + qBittorrent)
      run: |
        cd sdk
        make package/boost/compile V=s -j$(nproc) || true
        make package/rblibtorrent/compile V=s -j$(nproc) || true
        make package/qbittorrent/compile V=s -j$(nproc) || true

    - name: Upload all built IPKs
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-with-deps
        path: |
          sdk/bin/packages/**/*.ipk
