name: Build OpenWrt qBittorrent IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt7621/openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64 sdk

      - name: Add qBittorrent Package
        run: |
          cd sdk/package
          git clone https://github.com/openwrt/packages.git openwrt-packages
          mv openwrt-packages/net/qbittorrent .
          rm -rf openwrt-packages

      - name: Update Feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build qBittorrent
        run: |
          cd sdk
          make package/qbittorrent/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: qbittorrent-ipk
          path: sdk/bin/packages/*/base/qbittorrent*.ipk
