name: OpenWrt SDK Builder

on:
  workflow_dispatch:
    inputs:
      package:
        description: "要编译的包名（例如 qbittorrent 或 aria2）"
        required: true
        default: "qbittorrent"
      target:
        description: "OpenWrt target (默认 JDCloud RE-SP-01B: ramips/mt7621)"
        required: false
        default: "ramips/mt7621"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          TARGET=${{ github.event.inputs.target }}
          VERSION=23.05.3
          BASE_URL="https://downloads.openwrt.org/releases/$VERSION/targets"
          SDK_URL="$BASE_URL/$TARGET/openwrt-sdk-$VERSION-${TARGET//\//-}_gcc-12.3.0_musl.Linux-x86_64.tar.xz"

          wget $SDK_URL
          tar -Jxf openwrt-sdk-*.tar.xz

          rm -rf sdk
          mkdir sdk
          mv openwrt-sdk-*/. sdk/

      - name: Prepare feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build selected package
        run: |
          cd sdk
          make defconfig
          make package/${{ github.event.inputs.package }}/compile V=s -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipk-${{ github.event.inputs.package }}
          path: sdk/bin/packages/*/*/${{ github.event.inputs.package }}_*.ipk
