name: Build qBittorrent IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt7621/openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64 sdk

      - name: Clone qBittorrent package
        run: |
         cd sdk/package
         git clone https://github.com/c0re100/qBittorrent-openwrt-package.git
         mv qBittorrent-openwrt-package/qbittorrent ./qbittorrent
         rm -rf qBittorrent-openwrt-package


      - name: Update feeds
        run: |
          cd sdk
          echo "src-git packages https://git.openwrt.org/feed/packages.git;openwrt-23.05" >> feeds.conf.default
          echo "src-git luci https://git.openwrt.org/project/luci.git;openwrt-23.05" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure SDK
        run: |
          cd sdk
          make defconfig

      - name: Build qBittorrent
        run: |
          cd sdk
          make package/qbittorrent/compile -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qbittorrent-ipk
          path: sdk/bin/packages/*/*/qbittorrent*.ipk
