name: Build qBittorrent IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.2/targets/ramips/mt7621/immortalwrt-sdk-24.10.2-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf immortalwrt-sdk-24.10.2-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        mv immortalwrt-sdk-24.10.2-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64 sdk
        cd sdk && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Clone qBittorrent package
      run: |
        cd sdk/package
        git clone -b for-openwrt-19.07 https://github.com/KryptonLee/qBittorrent-openwrt-package.git qbittorrent
        ls -l qbittorrent

    - name: Build qBittorrent
      run: |
        cd sdk
        make defconfig
        make package/qbittorrent/compile -j$(nproc) V=sc

    - name: Upload IPK
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-ipk
        path: sdk/bin/packages/*/*/*.ipk
