name: Build qBittorrent IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python2.7 python2.7-dev unzip zlib1g-dev file wget
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python


    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/19.07.9/targets/ramips/mt7621/openwrt-sdk-19.07.9-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-19.07.9-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-19.07.9-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64 sdk
        cd sdk && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Clone qBittorrent package
      run: |
        cd sdk/package
        git clone -b for-openwrt-19.07 https://github.com/KryptonLee/qBittorrent-openwrt-package.git qbittorrent
        ls -l qbittorrent

    - name: Build qBittorrent
      run: |
        cd sdk
        make defconfig
        make package/qbittorrent/compile -j$(nproc) V=sc

    - name: Upload IPK
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-ipk
        path: sdk/bin/packages/*/*/*.ipk
